POST localhost:8080/user/complete/course?courseId=2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImV4cCI6MTY5OTQyOTI4NCwiZW1haWwiOiJ3cGVrZGwxNTNAZ21haWwuY29tIn0.t0pNUrdPtFr5sdyqeIKqXccHaW1YEfWd9nUW3ZmTxne__dXRGdNKELZxs3Ahu4yHBz5o7uET9S-UBa098tMElA
