### 수강신청
PUT localhost:8080/user/listen/course/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImV4cCI6MTY5ODkxNTAyMywiZW1haWwiOiJ3cGVrZGwxNTNAZ21haWwuY29tIn0.XmavLnj696SqK-Eg1-RikHHwSGkZoJQDW_MZXGX0_ekhQSAh9tbGhpr3SPxyzh9sKsLnNpv5nVVIxS9b_0dD-A
