POST localhost:8080/user/planner/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImV4cCI6MTY5OTUxMzYzMiwiZW1haWwiOiJ3cGVrZGwxNTNAZ21haWwuY29tIn0.POz0jMLvS2qkAai4lvhc5VXpei9kgfA_vQgIG5EWJaJvJGDJVFORRTOmV3RtIMcp1XMfH1EA2sTTOqMAIqyz7g
Content-Type: application/json

{
  "typeId": 1,
  "type": "REMINDER",
  "plannerDt": "2023-11-09"
}

### planner 날짜 변경
POST localhost:8080/user/planner/update
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImV4cCI6MTY5OTUxMzYzMiwiZW1haWwiOiJ3cGVrZGwxNTNAZ21haWwuY29tIn0.POz0jMLvS2qkAai4lvhc5VXpei9kgfA_vQgIG5EWJaJvJGDJVFORRTOmV3RtIMcp1XMfH1EA2sTTOqMAIqyz7g
Content-Type: application/json

{
  "plannerId": 1,
  "plannerDt": "2023-11-10"
}