### 회원가입
POST http://localhost:8080/join
Content-Type: application/json

{
  "email": "wpekdl153@gmail.com",
  "password": "123144",
  "nickName": "planner",
  "authType": "USER"
}

### 로그인
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "wpekdl153@gmail.com",
  "password": "123144"
}

### 토큰
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImV4cCI6MTY5OTA5MDg5NCwiZW1haWwiOiJ3cGVrZGwxNTNAZ21haWwuY29tIn0.4OMOh9PqRFlokkuyzyvkaCxrI_N7qLGwDQfLoV19vtaulGrW5oX-AA3HqQsZ1mwmEGtaW--6bjO1UkKDhMZx9A
Authorization-refresh: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJSZWZyZXNoVG9rZW4iLCJleHAiOjE2OTk2ODkwODB9.dOc-6SYTeuho-AWV91M8sOuWbE5GRZSo-LhAAalaALROn5HrZf6L1MKRF-SJGl_QBe2sf_4go9hTlpD8JigZZg